
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Michael Martínez
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        DefaultComboBoxModel x=(DefaultComboBoxModel)cb_sexo.getModel();
        x.addElement("Masculino");
        x.addElement("Femenino");
        
        cb_sexo.setModel(x);
        DefaultComboBoxModel y=(DefaultComboBoxModel)cb_deptos.getModel();
        y.addElement("Francisco Morazán");
        y.addElement("Cortés");
        y.addElement("Comayguas");
        
        cb_deptos.setModel(y);
        
        DefaultComboBoxModel w=(DefaultComboBoxModel)cb_usuarios.getModel();
        for (int i = 0; i < listaUsuarios.size(); i++) {
            if (listaUsuarios.get(i)instanceof civiles) {
                w.addElement(listaUsuarios.get(i));
            }
        }
        cb_usuarios.setModel(w);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_empleado = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        cb_usuarios = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_sexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_deptos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tf_nombreM = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jd_civil = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pf_contraseña = new javax.swing.JPasswordField();
        jb_ingresar = new javax.swing.JButton();

        jd_empleado.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("Información de los civiles: ");

        jLabel6.setText("Trámites");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "No. Identiidad", "Fecha de nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre trámite", "Descripción", "Fecha", "Numero identidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6))
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("INFORMACION CIVILES", jPanel1);

        cb_usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuariosItemStateChanged(evt);
            }
        });
        cb_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuariosActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre");

        jLabel8.setText("Contrasenia");

        jLabel9.setText("Sexo");

        jLabel10.setText("Departamento");

        jLabel11.setText("Apellido");

        jLabel12.setText("Fecha de nacimiento");

        jButton2.setText("MODIFICAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(179, 179, 179)
                                .addComponent(jLabel11))
                            .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(147, 147, 147)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_deptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cb_deptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("MODIFICACIÓN CIVILES", jPanel2);

        jLabel3.setText("Bienvenido");

        jButton1.setText("Cerrar sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_empleadoLayout = new javax.swing.GroupLayout(jd_empleado.getContentPane());
        jd_empleado.getContentPane().setLayout(jd_empleadoLayout);
        jd_empleadoLayout.setHorizontalGroup(
            jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empleadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_empleadoLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jd_empleadoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(41, 41, 41))))
        );
        jd_empleadoLayout.setVerticalGroup(
            jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_empleadoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(jButton1))
                .addGap(42, 42, 42)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jd_civil.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jd_civilLayout = new javax.swing.GroupLayout(jd_civil.getContentPane());
        jd_civil.getContentPane().setLayout(jd_civilLayout);
        jd_civilLayout.setHorizontalGroup(
            jd_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_civilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jd_civilLayout.setVerticalGroup(
            jd_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_civilLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");

        jl_nombre.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jl_nombre.setText("Nombre Completo");

        tf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombre.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Contraseña");

        pf_contraseña.setBackground(new java.awt.Color(255, 255, 255));
        pf_contraseña.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        pf_contraseña.setForeground(new java.awt.Color(0, 0, 0));

        jb_ingresar.setBackground(new java.awt.Color(153, 153, 255));
        jb_ingresar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jb_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        jb_ingresar.setText("INGRESAR");
        jb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarMouseClicked(evt);
            }
        });
        jb_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_nombre)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_contraseña)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jb_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jl_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jb_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void jb_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ingresarActionPerformed

    private void jb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarMouseClicked
        // TODO add your handling code here:
        String nombre=listaUsuarios.get(0).nombre+" "+listaUsuarios.get(0).apellido;
        String nombreCivil=listaUsuarios.get(1).nombre+" "+listaUsuarios.get(1).apellido;
        if (tf_nombre.getText().equalsIgnoreCase(nombre)&& new String (pf_contraseña.getPassword()).
                equalsIgnoreCase(listaUsuarios.get(0).contraseña)) {
            jLabel4.setText(nombre);
            nombre="";
            this.setVisible(false);
            jd_empleado.setVisible(true);
            jd_empleado.pack();
            DefaultTableModel x=(DefaultTableModel)jTable1.getModel();
            //x.setRowCount(0);
            for (int i = 0; i < listaUsuarios.size(); i++) {
                if (listaUsuarios.get(i) instanceof civiles) {
                    Object[] newRow = new Object[3];
                    newRow[0] = listaUsuarios.get(i).nombre;
                    newRow[1] = listaUsuarios.get(i).identidad;
                    newRow[2] = listaUsuarios.get(i).nacimiento;
                    x.addRow(newRow);
                }
            }
            jTable1.setModel(x);
            
            //segunda tabla
            DefaultTableModel y=(DefaultTableModel)jTable2.getModel();
            //y.setRowCount(0);
            for (int i = 0; i < listaUsuarios.size(); i++) {
                if (listaUsuarios.get(i) instanceof civiles) {
                    Object[] newRow = new Object[4];
                    for (int j = 0; j < ((civiles)listaUsuarios.get(i)).listaTramites.size();j++) {
                        newRow[0] = ((civiles) listaUsuarios.get(i)).listaTramites.get(j).nombre;
                        newRow[1] = ((civiles) listaUsuarios.get(i)).listaTramites.get(j).descripcion;
                        newRow[2] = ((civiles) listaUsuarios.get(i)).listaTramites.get(j).fecha;
                        newRow[3] = ((civiles) listaUsuarios.get(i)).identidad;
                        y.addRow(newRow);
                    }
                    
                }
            }
            jTable2.setModel(y);
            
        }else if(tf_nombre.getText().equalsIgnoreCase(nombreCivil)&& new String (pf_contraseña.getPassword()).
                equalsIgnoreCase(listaUsuarios.get(1).contraseña)){
            jLabel4.setText(nombre);
            nombreCivil="";
            this.setVisible(false);
            jd_civil.setVisible(true);
            jd_civil.pack();
            
        }else{
            tf_nombre.setText("");
            pf_contraseña.setText("");
            JOptionPane.showMessageDialog(this, "Usuario incorrecto");
            
        }
            
    }//GEN-LAST:event_jb_ingresarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       tf_nombre.setText("");
       pf_contraseña.setText("");
        jd_empleado.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void cb_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuariosActionPerformed

    private void cb_usuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuariosItemStateChanged
        // TODO add your handling code here:
        
        tf_nombreM.setText(((civiles)cb_usuarios.getSelectedItem()).nombre);
        tf_apellido.setText(((civiles)cb_usuarios.getSelectedItem()).apellido);
        tf_contra.setText(((civiles)cb_usuarios.getSelectedItem()).contraseña);
        if (((civiles)cb_usuarios.getSelectedItem()).sexo.equalsIgnoreCase("Masculino")) {
            cb_sexo.setSelectedIndex(0);
        }else if(((civiles)cb_usuarios.getSelectedItem()).sexo.equalsIgnoreCase("Femenino")){
            cb_sexo.setSelectedIndex(1);
        }
        if (((civiles)cb_usuarios.getSelectedItem()).departamento.equalsIgnoreCase("Francisco Morazán")) {
            cb_deptos.setSelectedIndex(0);
        }else if(((civiles)cb_usuarios.getSelectedItem()).departamento.equalsIgnoreCase("Francisco Morazán")){
            cb_deptos.setSelectedIndex(1);
        }else if(((civiles)cb_usuarios.getSelectedItem()).departamento.equalsIgnoreCase("Francisco Morazán")){
            cb_deptos.setSelectedIndex(2);
        }
    }//GEN-LAST:event_cb_usuariosItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String nombre, apellido,contraseña,sexo,departamento;
        Date fecha;
        nombre=tf_nombreM.getText();
        apellido=tf_apellido.getText();
        contraseña=tf_contra.getText();
        sexo=cb_sexo.getSelectedItem().toString();
        departamento=cb_deptos.getSelectedItem().toString();
        fecha=jCalendar1.getDate();
        for (int i = 0; i < listaUsuarios.size(); i++) {
            if (cb_usuarios.getSelectedItem().toString().equalsIgnoreCase(listaUsuarios.get(i).identidad)) {
                listaUsuarios.get(i).setApellido(apellido);
                listaUsuarios.get(i).setNombre(nombre);
                listaUsuarios.get(i).setContraseña(contraseña);
                listaUsuarios.get(i).setSexo(sexo);
                listaUsuarios.get(i).setDepartamento(departamento);
                listaUsuarios.get(i).setNacimiento(fecha);
            }
        }
        
        JOptionPane.showMessageDialog(rootPane, "Usuario modificado con éxito");
        proceso();
    }//GEN-LAST:event_jButton2MouseClicked
    
    private void proceso(){
        // TODO add your handling code here:
     
//       jTable2.setModel(new DefaultTableModel());
//        
        DefaultTableModel x=(DefaultTableModel)jTable1.getModel();
        x.setRowCount(0);
            //x.setRowCount(0);
            for (int i = 0; i < listaUsuarios.size(); i++) {
                if (listaUsuarios.get(i) instanceof civiles) {
                    Object[] newRow = new Object[3];
                    newRow[0] = listaUsuarios.get(i).nombre;
                    newRow[1] = listaUsuarios.get(i).identidad;
                    newRow[2] = listaUsuarios.get(i).nacimiento;
                    x.addRow(newRow);
                }
            }
            jTable1.setModel(x);
            
            //segunda tabla
            
            DefaultTableModel y=(DefaultTableModel)jTable2.getModel();
            
            y.setRowCount(0);
            
            for (int i = 0; i < listaUsuarios.size(); i++) {
                if (listaUsuarios.get(i) instanceof civiles) {
                    Object[] newRow = new Object[4];
                    for (int j = 0; j < ((civiles)listaUsuarios.get(i)).listaTramites.size();j++) {
                        newRow[0] = ((civiles) listaUsuarios.get(i)).listaTramites.get(j).nombre;
                        newRow[1] = ((civiles) listaUsuarios.get(i)).listaTramites.get(j).descripcion;
                        newRow[2] = ((civiles) listaUsuarios.get(i)).listaTramites.get(j).fecha;
                        newRow[3] = ((civiles) listaUsuarios.get(i)).identidad;
                        y.addRow(newRow);
                    }
                    
                }
            }
            jTable2.setModel(y);
    }
    
    
    /**
     * @param args the command line arguments
     */
    //FILA 2, ASIENTO 7
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //AGREGAR USUARIOS
        
        //AGREGAR EMPLEADO
        usuarios empleado=new empleado("Ing. Sistemas", "Administrador",
                15, "Emilio", "Cantarero",
                "sistema12", "Masculino", "Francisco Morazán",
                "", (new Date(2002, 5, 15)));
        
        listaUsuarios.add(empleado);
                
        //AGREGAR CIVIL
        usuarios civil=new civiles("Michael", "Martinez", "mike123",
                "Masculino", "Francisco Morazán", "",
                (new Date(2003, 8, 14)));
        listaUsuarios.add(civil);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    public static ArrayList<usuarios>listaUsuarios=new ArrayList();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_deptos;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JComboBox<String> cb_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jb_ingresar;
    private javax.swing.JDialog jd_civil;
    private javax.swing.JDialog jd_empleado;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JPasswordField pf_contraseña;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreM;
    // End of variables declaration//GEN-END:variables
}
